---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.vue"
exclude_paths:
- config/
- test/
