language: node_js
node_js:
- node
addons:
  sauce_connect:
    username: logan12358
  jwt:
    secure: "e1yIQM+NDV4EGUJH0ixhN7Xq5etFtTR0x+pk9/CaBddyimzFyQAiqbFalkbil8r5K4eNcC+g5ATAimrw8jrMOiyz7xpcECrkMhCEhVvP3jOZukA+aRMvTz6oqY5Me+8OZxnZqXuHEs3fF/9/eNxHS8td084RmMDy0PgMvk5QV2aiXL2ByOwkB2vYkma+7IioSzmIinJJ8jUDdMZaF+00ejA+5Oybvus6octwpjYS2grqnKEGu9pdeQBm/OqOoHIlsVPk0lzhjOFXYNmCRS4aCv6xtPVKh7rSig0InPeCkwg90OfIxSMxiBQ9m7GBH+xn+crI7+9SYcJD3WmDRhvBWLxJMP2VuINHDYVfpoTDUBg1fnhPuS5YIATRtsIi/lOkX7Dj21SsdxyRg8KygAh31qWIssb9rkK3E4atrGr40me2aCFVZGXoupl86HNyL23QI0fEeJzqe9ypx3vBrRx/+8ES5c7vXrUBo4cu1VFHuh7k5N+//PlV3SU9nMj9aauFGPepbqER9Gl3qTup4JfvMEOiTebQat63UEJDm8lAKWNxqJEPveoDlcDQ+LYmX+p6jTgzBE/YM4taUfbVIQf3W0llQS7KHMrgZC4vzqIa5644U9Rx/pwShqX8jPXHgyGuS5d1OfwfuNu7qRF/iSlTW3nP2exJtj9Fq6G7Kb5Tw8Q="
