language: node_js
node_js:
- node
addons:
  sauce_connect:
    username: logan12358
  jwt:
    secure: W1bj8+BV6+34BumbmYF8UlGa0LQy9f3Qf3wN+xxF+ZcGorae3/ld0KkfIqrdwkSfhsU1zXyI1C4vKwi8AIMkAc32rQqdvjxhjblkgWdduiYLu3/O/uFJglvcVeqttb3Z+3EAr4yGzFty34Svj9SW6GNu+v6PeqQQ46ZFXQPhbBZI6kGDJL5tzbVVABwG7yrzrrtp1QKYYUpnxDdC6LC/Ay6ycPm/E2zy6VBr39YnKZT+NLkfnbAXEC7i0Kx6t8HsmSwQ2Al0gTsiPkIMO3cPdWmuFAUTSfvB1kH/QEgs6Kb0XcILj2wnVROTGLRpBKgYddKejKeDD6bvyXyBm1fw+tz42pFxc4pxgV3hjHRVOVqGJdK31c6GSNLO746k3yLgUItMkC0JT99g4j11Xkl2jkUzhusNF0V4X11ebFPqOS5rmLgqBfgQh3fqTOJ9kHZxbBsslA7kyWJoiDK8pLvIk+YXtjZwnI+uSuYh66E5uDQxROdzdSbg5Qj+EgK1GSvs3Vpqlbx37UpcBGMyE+lDljbXVFf4PV4zRTRZvsZFl8bQQ2OT6RzQ74rFY/ynQd0Toi5w+lb2PxabpaZEuXJEIyIav29q3Zw4Usz1FIInqpCpQUYkc3YT4ViYlGhGsTPh5EdH+SpQcyJHRmjGMeddTlyLd1KmPSCySpcettixSSg=
